### ISSUE TITLE
CMake cannot find MKL on 32 bit machines

### ISSUE THREAD

**Issue by pflaquerre** [torch/DEPRECEATED-torch7-distro#12]
From /lib/TH/cmake/FindMKL.cmake:

```
CHECK_TYPE_SIZE("void*" SIZE_OF_VOIDP)
IF ("${SIZE_OF_VOIDP}" EQUAL 8)
  SET(mklvers "em64t")
  SET(iccvers "intel64")
  SET(mkl64s "_lp64")
ELSE ("${SIZE_OF_VOIDP}" EQUAL 8)
  SET(mklvers "32")
  SET(iccvers "ia32")
  SET(mkl64s)
ENDIF ("${SIZE_OF_VOIDP}" EQUAL 8)
```

which will give you an empty mkl64s on 32 bit machines. Further down in the same file, all calls to `CHECK_ALL_LIBRARIES` are wrapped around by `FOREACH(mkl64 ${mkl64s} "")` (except for really old mkl versions). CMake's Modules/FindBLAS.cmake seems to handle this properly, so it's just a matter of integrating their checks in.

**Comment by andresy** [comment]
Hmmm... I do not get what you mean.

Yes, mkl64s is empty on 32 machines (I do not have any btw, I did not know it still existed ;)), and that is correct. (I do not think I changed FindMKL since a long time, and it used to work on 32 bit machines).
Yes, there is a loop which goes around ${mkl64s} and "", so things like mkl_intel_em64t or mkl_intel will be tested, and I believe this is correct too.

Did you check which libraries were not found on your computer?
Beware that both the MKL libraries and the intel compiler libraries must be found in CMAKE_LIBRARY_PATH (or LD_LIBRARY_PATH). In my case, I have something like what is written there:
http://www.torch.ch/manual/install/blas#cmake_detection1
