### ISSUE TITLE
Difference: SpatialFullConvolutionMap/SpatialConvolutionMap

### ISSUE THREAD

**Issue by ogh** [torch/DEPRECEATED-torch7-distro#123]
Hey!
I'm wondering what the difference between a SpatialConvolutionMap with a full connection table and a SpatialFullConvolutionMap is.
Unfortunately, I couldn't find any documentation for SpatialFullConvolutionMap and am having trouble getting this information from the source code.

Thanks in advance!

**Comment by koraykv** [comment]
The SpatialConvolutionMap computes a valid convolution of input with its kernels.
The SpatialFullConvolutionMap computes a full convolution of input with its kernels.

For a valid convolution, the output is smaller than the input due to the boundary effect of the convolution.
size_valid_conv(x,k,s) = x-k+1

For a full convolution the output is larger than the input.
size_full_conv(x,k,s) = x+k-1

These are assuming the strides are 1, but the difference is same anyways.

**Comment by ogh** [comment]
Thank you very much for your quick and detailed reply!
