### ISSUE TITLE
torch-pkg re-installs all dependencies everytime

### ISSUE THREAD

**Issue by jucor** [torch/DEPRECEATED-torch7-distro#137]
Hi guys

I noticed that torch-pkg reinstalls every dependency everytime, even if those are up-to-date. I think we discussed it offline with Koray a while ago, who said it was indeed possible. It makes installing packages a long process, either when there are cascading dependencies with duplicated leaves. Example1: installing package A who needs B and C and D, and both B and C need D: D is installed/compiled 3 times. 

Any idea if it would be easy to add a check and avoid this behaviour ?
Thanks !

**Comment by clementfarabet** [comment]
The reason it was done this way is because we don't have version support in torch-pkg. This is a simple way of insuring that when you deploy a package, all the dependencies are pulled and installed from their latest version (git heads).

To fix that, we would need to have some form of manifest that describes installed packages, their state, so that torch-pkg only installs outdated versions. But note that it would still need to pull each dependency to verify that the latest commit in each package has the same commit hash as the one installed locally.

**Comment by jucor** [comment]
Thanks for the details, it all makes sense. 
Do we really need the manifest? Wouldn't it be sufficient to  pulling the dependency and compare its commit to the one currently checked out in the install folder?

**Comment by clementfarabet** [comment]
Yeah it could be done like this!
